version: 2.1
executors:
    docker-publisher:
        environment:
            IMAGE_NAME: gnuton/asuswrt-merlin-toolchains-docker
        docker:
            - {image: 'circleci/buildpack-deps:stretch'}
jobs:
    build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - {run: {name: 'Build Latest Docker image', command: 'docker build -t $IMAGE_NAME:latest .'}}
            - {run: {name: 'Build Tagged Docker image', command: 'export DOCKER_TAG=$(date +%Y%m%d); docker build -t $IMAGE_NAME:${DOCKER_TAG} .'}}  
            - {run: {name: 'Archive Latest Docker image', command: 'docker save -o image_latest.tar $IMAGE_NAME:latest'}}
            - {run: {name: 'Archive Tagged Docker image', command: 'export DOCKER_TAG=$(date +%Y%m%d); docker save -o image_tagged.tar $IMAGE_NAME:${DOCKER_TAG}'}}  
            - {persist_to_workspace: {root: ., paths: [./image_latest.tar]}}
            - {persist_to_workspace: {root: ., paths: [./image_tagged.tar]}}  
    publish:
        executor: docker-publisher
        steps:
            - {attach_workspace: {at: /tmp/workspace}}
            - setup_remote_docker
            - {run: {name: 'Load archived Latest Docker image', command: 'docker load -i /tmp/workspace/image_latest.tar'}}
            - {run: {name: 'Load archived Tagged Docker image', command: 'docker load -i /tmp/workspace/image_tagged.tar'}}  
            - {run: {name: 'Publish Docker Latest Image to Docker Hub', command: "echo \"$DOCKERHUB_PASS\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin\ndocker push $IMAGE_NAME:latest\n"}}
            - {run: {name: 'Publish Docker Tagged Image to Docker Hub', command: "export DOCKER_TAG=$(date +%Y%m%d); echo \"$DOCKERHUB_PASS\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin\ndocker push $IMAGE_NAME:${DOCKER_TAG}\n"}}

              
workflows:
    version: 2
    build-master:
        jobs:
            - {build: {filters: {branches: {only: master}}}}
            - {publish: {requires: [build], filters: {branches: {only: master}}}}
